name: Generate Snake Contribution Animation

on:
  # Run automatically every 1 hours
  schedule:
    - cron: "0 */24 * * *" 

  # Allows manual trigger
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main  # Change 'main' to 'master' if needed

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write  # This grants permission to push changes

    steps:
      # Checkout the repository with write permission
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # Ensure credentials are kept for pushing

      # Generate the snake animation
      - name: Generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: MahekVanjani611
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit and push changes
      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake-dark.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
